export type ViewState = 
  | 'home' 
  | 'chat' 
  | 'search' 
  | 'writer' 
  | 'image' 
  | 'video' 
  | 'voice' 
  | 'translate' 
  | 'pdf' 
  | 'coding' 
  | 'subscriptions' 
  | 'wallet' 
  | 'notifications' 
  | 'profile' 
  | 'settings' 
  | 'admin';
